### PR TITLE
Moved examples from web to example directory

### PR DESCRIPTION
**Pull request by Scorpiion**
Fix for issue #113.

Note: I have signed the CLA.

### CODE REVIEW

**Comment by psunkari** [comment]
Could you sync this to the latest please.
Thank you for the change.

**Comment by Scorpiion** [comment]
Hi @psunkari, it should be synced with your latest changes now.

**Comment by psunkari** [comment]
Thanks for the change, Robert.

**Comment by Scorpiion** [comment]
No problem! :)

**Pull request merged**
